### ISSUE TITLE
New message works with permission only

### ISSUE THREAD

**Issue by SeussCZ** [jaqobb-mineground/message-editor#41]
Hi, New message works with permission "messageeditor.use" only, If I dont have this permission, I se old message and this error is in the console.

`[19:26:27 INFO]: Seuss issued server command: /is
[19:26:27 ERROR]: [MessageEditor] Unhandled exception occurred in onPacketSending(PacketEvent) for MessageEditor
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
at com.google.gson.Gson.assertFullConsumption(Gson.java:1135) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1125) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:969) ~[gson-2.10.jar:?]
at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[adventure-text-serializer-gson-4.14.0.jar:?]
at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[adventure-text-serializer-gson-4.14.0.jar:?]
at dev.jaqobb.message_editor.util.MessageUtils.updateMessage(MessageUtils.java:350) ~[message-editor-2.5.3-all.jar:?]
at dev.jaqobb.message_editor.message.MessagePlace$2.setMessage(MessagePlace.java:65) ~[message-editor-2.5.3-all.jar:?]
at dev.jaqobb.message_editor.listener.packet.ChatPacketListener.onPacketSending(ChatPacketListener.java:167) ~[message-editor-2.5.3-all.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2162) ~[?:?]
at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1977) ~[?:?]
at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1972) ~[?:?]
at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:320) ~[paper-1.20.1.jar:git-Paper-84]
at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:310) ~[paper-1.20.1.jar:git-Paper-84]
at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:327) ~[paper-1.20.1.jar:git-Paper-84]
at com.sk89q.worldedit.bukkit.BukkitPlayer.printRaw(BukkitPlayer.java:112) ~[worldedit-bukkit-7.2.15.jar:?]
at com.sk89q.worldguard.bukkit.BukkitPlayer.printRaw(BukkitPlayer.java:213) ~[worldguard-bukkit-7.0.9-beta1.jar:?]
at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.formatAndSendDenyMessage(RegionProtectionListener.java:123) ~[worldguard-bukkit-7.0.9-beta1.jar:?]
at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerCommandPreprocess(WorldGuardPlayerListener.java:428) ~[worldguard-bukkit-7.0.9-beta1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor154.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-84]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-84]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-84]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2275) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-84]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar:?]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.jar:?]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
at com.google.gson.Gson.assertFullConsumption(Gson.java:1131) ~[gson-2.10.jar:?]
... 55 more
[19:26:27 ERROR]: Parameters:
net.minecraft.network.protocol.game.ClientboundSystemChatPacket@6c8503a8[
content=<null>
b=false
]`

**Comment by jaqobb** [comment]
Hello, I am sorry for not responding. A few updates were released in the meantime, can you try updating and see if the issue persists? If so, please create a new issue with up to date error message alongside some other valuable information like other plugins etc.
